parameters:
    tables.primetime.categories: %core.table_prefix%categories
    tables.primetime.categories_data: %core.table_prefix%categories_data

services:

    primetime.category.display:
        class: primetime\category\core\display
        arguments:
            - @dbal.conn
            - @primetime
            - %tables.primetime.categories%
            - 'cat_id'

    primetime.category.manager:
        class: primetime\category\core\builder
        arguments:
            - @dbal.conn
            - @primetime
            - %tables.primetime.categories%
            - 'cat_id'

    primetime.category.admin:
        class: primetime\category\controller\admin
        arguments:
            - @request
            - @user
            - @primetime.category.manager

# Blocks
    primetime.block.categories:
        class: primetime\category\blocks\categories
        arguments:
            - @dbal.conn
            - @user
            - @primetime.category.display
        calls:
            - [set_name, [primetime.block.categories]]
        tags:
            - { name: primetime.block }