parameters:
    tables.primetime.categories: %core.table_prefix%pt_categories
    tables.primetime.categories_data: %core.table_prefix%pt_categories_data

services:

    primetime.category.display:
        class: primetime\category\core\display
        arguments:
            - @dbal.conn
            - @primetime
            - %tables.primetime.categories%
            - 'cat_id'

    primetime.category.manager:
        class: primetime\category\core\builder
        arguments:
            - @cache.driver
            - @dbal.conn
            - @primetime
            - %tables.primetime.categories%
            - 'cat_id'

    primetime.category.admin.controller:
        class: primetime\category\controller\admin
        arguments:
            - @dbal.conn
            - @request
            - @user
            - @primetime.category.manager

    primetime.category.items.controller:
        class: primetime\category\controller\items
        arguments:
            - @dbal.conn
            - @request
            - @user
            - @primetime.category.manager

    form.field.category:
        class: primetime\category\core\form_field
        arguments:
            - @dbal.conn
            - @controller.helper
            - @request
            - @primetime.template
            - @primetime.category.display
            - %tables.primetime.categories_data%
        tags:
            - { name: form.field }

    primetime.category.listener:
        class: primetime\category\event\listener
        tags:
            - { name: event.listener }

# Blocks
    primetime.block.categories:
        class: primetime\category\blocks\categories
        arguments:
            - @dbal.conn
            - @primetime.category.display
        calls:
            - [set_name, [primetime.block.categories]]
        tags:
            - { name: primetime.block }